import {esc,money,dateTime,source,button} from '../../shared/feature-ui.js';
const asset=file=>`/assets/schools/bjfu/${file}`;
const products=new Map([['北林校园风物笔记本',asset('culture-notebook.png')],['四季北林·森语同行',asset('culture-seasons.png')],['龙林时藏——北林文创文具',asset('culture-stationery.png')]]);
const productOrder = title => products.has(title) ? [...products.keys()].indexOf(title) : products.size;
const leaf=`<svg viewBox="0 0 100 90" aria-hidden="true"><path d="M48 66C24 62 5 36 7 22 20 24 29 8 43 5 48 21 52 20 59 4 74 9 88 22 95 27 90 43 74 61 53 66L64 86 59 89Z" fill="currentColor"/><path d="M49 63 25 20M50 63 46 13M52 62 69 16M53 63 85 31" fill="none" stroke="#fff5dc" stroke-width="1.5"/></svg>`;
const icon=kind=>kind==='gift'?`<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M6 20h36v8H6zm4 11h28v13H10zM21 20h6v24h-6zM23 18C4 20 9 1 17 6c5 3 7 12 7 12S27 4 34 6c11 4 0 14-11 12Z" fill="currentColor"/></svg>`:`<svg viewBox="0 0 48 48" aria-hidden="true"><path d="m13 3-10 17h5L0 33h10v8h6v-8h10l-8-13h5L13 3Zm23 5-8 15h4l-7 13h8v6h6v-6h9l-8-13h4L36 8Z" fill="currentColor"/></svg>`;
function sectionHeading(title,description,kind){return `<header class="bjfu-culture-section-heading"><span class="bjfu-culture-section-icon">${icon(kind)}</span><h2>${title}</h2><p>${description}</p><i aria-hidden="true"></i></header>`;}
function eventPoster(event){
 // The supplied composition illustrates the campus; titles and dates remain live records.
 const crop=[72,370,365,225];
 return `<svg class="bjfu-event-poster" viewBox="${crop.join(' ')}" role="img" aria-label="北林校园文化插画" preserveAspectRatio="xMidYMid slice" overflow="hidden"><defs><clipPath id="bjfu-poster-${event.id}"><rect x="${crop[0]}" y="${crop[1]}" width="${crop[2]}" height="${crop[3]}"/></clipPath></defs><image href="${asset('culture-reference.png')}" width="1672" height="941" clip-path="url(#bjfu-poster-${event.id})"/></svg>`;
}
function action(text,kind,id,primary=false){return button(text,kind,primary).replace(`data-action="${kind}"`,`data-action="${kind}" data-id="${id}"`);}
export function bjfuCulturePage({activities,items,points,orders,signups}){
 return `<div class="bjfu-culture-page"><section class="bjfu-culture-hero" aria-label="北林风华 绿意相传"><svg class="bjfu-culture-panorama" viewBox="0 80 1672 270" role="img" aria-label="北林风华 绿意相传，以林为底色，与青春同行；北京林业大学校门与竹构建筑，两侧校园书法" preserveAspectRatio="xMidYMid meet"><defs><linearGradient id="bjfu-hero-edge" x1="0" y1="80" x2="0" y2="298" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="white"/><stop offset=".85" stop-color="white"/><stop offset="1" stop-color="black"/></linearGradient><linearGradient id="bjfu-hero-stone" x1="0" y1="80" x2="0" y2="350" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="white"/><stop offset=".90" stop-color="white"/><stop offset="1" stop-color="black"/></linearGradient><mask id="bjfu-hero-art" maskUnits="userSpaceOnUse" x="0" y="80" width="1672" height="270"><rect x="0" y="80" width="740" height="270" fill="url(#bjfu-hero-edge)"/><rect x="740" y="80" width="710" height="270" fill="url(#bjfu-hero-stone)"/><rect x="1450" y="80" width="222" height="270" fill="url(#bjfu-hero-edge)"/></mask></defs><image href="${asset('culture-reference.png')}" width="1672" height="941" mask="url(#bjfu-hero-art)"/></svg><h1 class="bjfu-culture-sr">北林风华 绿意相传</h1></section>
 <section class="bjfu-culture-section">${sectionHeading('校园活动','丰富多彩的校园文化活动，期待你的参与','campus')}<div class="bjfu-culture-events">${activities.map(x=>`<article class="bjfu-culture-event">${eventPoster(x)}<div class="bjfu-culture-card-copy"><div class="bjfu-culture-title"><h3>${esc(x.title)}</h3><span>校园活动</span></div><p class="bjfu-culture-description">${esc(x.description)}</p><p class="bjfu-culture-meta"><span aria-hidden="true">⌖</span>${esc(x.campus)} · ${esc(x.location)}</p><p class="bjfu-culture-meta"><span aria-hidden="true">◷</span>${esc(dateTime(x.startsAt))} — ${esc(dateTime(x.endsAt))}</p>${source(x.sourceName,x.startsAt)}${action('报名参加','join',x.id,true)}</div><span class="bjfu-card-leaf" aria-hidden="true">${leaf}</span></article>`).join('')||'<p>暂无活动。</p>'}</div></section>
 <section class="bjfu-culture-section">${sectionHeading('校园文创与积分兑换','把北林的四季与美好，带回你的日常生活','gift')}<div class="bjfu-culture-products">${[...items].sort((a,b)=>productOrder(a.title)-productOrder(b.title)).map(x=>`<article class="bjfu-culture-product">${(products.has(x.title)||x.image)?`<img src="${esc(x.image || products.get(x.title))}" alt="${esc(x.title)}" loading="lazy">`:`<div class="bjfu-product-fallback">${icon('gift')}</div>`}<div class="bjfu-culture-card-copy"><h3>${esc(x.title)}</h3><p class="bjfu-culture-description">${esc(x.description)}</p><p class="bjfu-product-price"><strong>${money(x.price)}</strong> · 库存 ${esc(x.stock)}</p>${source(x.sourceName)}<div class="bjfu-culture-actions">${action('确认购买','buy',x.id,true)}${action('积分兑换','redeem',x.id)}</div></div></article>`).join('')||'<p>暂无文创商品。</p>'}</div></section>
 <div class="bjfu-culture-account"><section class="bjfu-culture-points"><header>${icon('gift')}<h2>校园积分</h2></header><strong class="bjfu-points-balance">${esc(points.balance)}<small>积分</small></strong><p>活动参与和菜品共创获得积分，可兑换校园文创。</p><div>${points.redemptions.map(r=>`<p>${esc(r.title)} · ${esc(r.status)}</p>`).join('')}</div><span class="bjfu-card-leaf" aria-hidden="true">${leaf}</span></section><section class="bjfu-culture-history"><h2>我的参与与文创订单</h2><div>${signups.map(x=>`<p>${esc(x.title)} · ${esc(x.signupStatus)} · ${esc(dateTime(x.startsAt))}</p>`).join('')}${orders.map(x=>`<p>${esc(x.title)} × ${x.quantity} · ${money(x.total)} · ${esc(x.status)}</p>`).join('')||'<p>暂无文创订单。</p>'}</div></section></div><div data-status></div></div>`;
}

export const isBjfuCultureAccount = account => Boolean(account?.token && account?.user?.school_id === "bjfu");
