import {esc,money,dateTime,source,button} from '../../shared/feature-ui.js';
const asset=file=>`/assets/zhongcai/${encodeURIComponent(file)}`;
const products=new Map(['中财校园风物笔记本','四季中财·逐光而行','龙马时藏——中财文创文具'].map(title=>[title,asset(title+'.png')]));
const leaf=`<svg viewBox="0 0 100 90" aria-hidden="true"><path d="M48 66C24 62 5 36 7 22 20 24 29 8 43 5 48 21 52 20 59 4 74 9 88 22 95 27 90 43 74 61 53 66L64 86 59 89Z" fill="currentColor"/><path d="M49 63 25 20M50 63 46 13M52 62 69 16M53 63 85 31" fill="none" stroke="#fff5dc" stroke-width="1.5"/></svg>`;
const icon=kind=>kind==='gift'?`<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M6 20h36v8H6zm4 11h28v13H10zM21 20h6v24h-6zM23 18C4 20 9 1 17 6c5 3 7 12 7 12S27 4 34 6c11 4 0 14-11 12Z" fill="currentColor"/></svg>`:`<svg viewBox="0 0 48 48" aria-hidden="true"><path d="m24 3 20 13H4zm-17 16h34v5H7zm4 8h6v12h-6zm10 0h6v12h-6zm10 0h6v12h-6zM5 40h38v5H5z" fill="currentColor"/></svg>`;
function sectionHeading(title,description,kind){return `<header class="cufe-culture-section-heading"><span class="cufe-culture-section-icon">${icon(kind)}</span><h2>${title}</h2><p>${description}</p><i aria-hidden="true"></i></header>`;}
function eventPoster(event){
 const crops={'中财校园文化与文创展':[66,356,331,248],'首届文创设计大赛':[821,356,330,248]};
 const crop=crops[event.title];
 if(!crop)return `<div class="cufe-event-poster-fallback">${icon('campus')}<span>${esc(event.title)}</span></div>`;
 // Display only the supplied poster region; no screenshot controls are interactive.
 return `<svg class="cufe-event-poster" viewBox="${crop.join(' ')}" role="img" aria-label="${esc(event.title)}海报" preserveAspectRatio="xMidYMid meet" overflow="hidden"><defs><clipPath id="cufe-poster-${event.id}"><rect x="${crop[0]}" y="${crop[1]}" width="${crop[2]}" height="${crop[3]}"/></clipPath></defs><image href="${asset('界面示意图.png')}" width="1586" height="992" clip-path="url(#cufe-poster-${event.id})"/></svg>`;
}
function action(text,kind,id,primary=false){return button(text,kind,primary).replace(`data-action="${kind}"`,`data-action="${kind}" data-id="${id}"`);}
export function cufeCulturePage({activities,items,points,orders,signups}){
 return `<div class="cufe-culture-page"><section class="cufe-culture-hero"><span class="cufe-culture-kicker">中央财经大学 · 校园文化</span><h1>中财风华 <span>文化相传</span></h1><p><i></i>以文化之名 · 绘青春之卷<i></i></p><small>CENTRAL UNIVERSITY OF FINANCE AND ECONOMICS</small><span class="cufe-culture-seal" aria-hidden="true">中财</span></section>
 <section class="cufe-culture-section">${sectionHeading('校园活动','丰富多彩的校园文化活动，期待你的参与','campus')}<div class="cufe-culture-events">${activities.map(x=>`<article class="cufe-culture-event">${eventPoster(x)}<div class="cufe-culture-card-copy"><div class="cufe-culture-title"><h3>${esc(x.title)}</h3><span>校园活动</span></div><p class="cufe-culture-description">${esc(x.description)}</p><p class="cufe-culture-meta"><span aria-hidden="true">⌖</span>${esc(x.campus)} · ${esc(x.location)}</p><p class="cufe-culture-meta"><span aria-hidden="true">◷</span>${esc(dateTime(x.startsAt))} — ${esc(dateTime(x.endsAt))}</p>${source(x.sourceName,x.startsAt)}${action('报名参加','join',x.id,true)}</div><span class="cufe-card-leaf" aria-hidden="true">${leaf}</span></article>`).join('')||'<p>暂无活动。</p>'}</div></section>
 <section class="cufe-culture-section">${sectionHeading('校园文创与积分兑换','将中财记忆带回家 · 用文创点亮校园生活','gift')}<div class="cufe-culture-products">${items.map(x=>`<article class="cufe-culture-product">${products.has(x.title)?`<img src="${products.get(x.title)}" alt="${esc(x.title)}" loading="lazy">`:`<div class="cufe-product-fallback">${icon('gift')}</div>`}<div class="cufe-culture-card-copy"><h3>${esc(x.title)}</h3><p class="cufe-culture-description">${esc(x.description)}</p><p class="cufe-product-price"><strong>${money(x.price)}</strong> · 库存 ${esc(x.stock)}</p>${source(x.sourceName)}<div class="cufe-culture-actions">${action('确认购买','buy',x.id,true)}${action('积分兑换','redeem',x.id)}</div></div></article>`).join('')||'<p>暂无文创商品。</p>'}</div></section>
 <div class="cufe-culture-account"><section class="cufe-culture-points"><header>${icon('gift')}<h2>校园积分</h2></header><strong class="cufe-points-balance">${esc(points.balance)}<small>积分</small></strong><p>活动参与和菜品共创获得积分，可兑换校园文创。</p><div>${points.redemptions.map(r=>`<p>${esc(r.title)} · ${esc(r.status)}</p>`).join('')}</div><span class="cufe-card-leaf" aria-hidden="true">${leaf}</span></section><section class="cufe-culture-history"><h2>我的参与与文创订单</h2><div>${signups.map(x=>`<p>${esc(x.title)} · ${esc(x.signupStatus)} · ${esc(dateTime(x.startsAt))}</p>`).join('')}${orders.map(x=>`<p>${esc(x.title)} × ${x.quantity} · ${money(x.total)} · ${esc(x.status)}</p>`).join('')||'<p>暂无文创订单。</p>'}</div></section></div><div data-status></div></div>`;
}

export const isCufeCultureAccount = account => Boolean(account?.token && account?.user?.school_id === "cufe");
