import { api,esc,money,dateTime,button,options,field,notice,bind,dialog,formData } from '../../shared/feature-ui.js';
const boards=[['recommend','封神推荐榜','fire-flame-curved'],['costEffective','极致性价比榜','piggy-bank'],['pitfall','踩雷避坑榜','bolt']];
const stars=n=>n?`<span class="square-stars" aria-label="${n}星">${'★'.repeat(Math.round(n))}${'☆'.repeat(5-Math.round(n))}</span>`:'';
const imageUrl=v=>{if(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v||''))return v;try{const u=new URL(v,location.origin);return v&&['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const trend=r=>r.change===null?'<small class="square-new">新上榜</small>':r.change>0?`<span class="square-trend up"><i class="fa-solid fa-arrow-up"></i> ${r.change}</span>`:r.change<0?`<span class="square-trend down"><i class="fa-solid fa-arrow-down"></i> ${-r.change}</span>`:'<small>— 持平</small>';
function rankRows(rows,key,detail=false){return rows.map((r,i)=>`<div class="square-rank-row"><em>${r.rank||i+1}</em>${detail&&imageUrl(r.image)?`<img class="square-rank-image" src="${esc(imageUrl(r.image))}" alt="${esc(r.name)}">`:''}<div class="square-rank-info"><b>${esc(r.name)}</b><small>${money(r.price)}</small>${detail?`<small>${esc(r.campus)} · ${esc(r.restaurant)} · ${esc(r.floor||'楼层待核实')}</small>`:''}${r.rating!=null?`<small>${esc(r.rating)}分 · ${r.reviews}条评价</small>`:''}</div>${detail?`${trend(r)}<button class="square-vote ${r.voted?'liked':''}" data-action="vote" data-id="${r.id}" aria-label="${key==='pitfall'?'点踩':'收藏'}${esc(r.name)}" aria-pressed="${r.voted}"><i class="fa-${r.voted?'solid':'regular'} fa-${key==='pitfall'?'thumbs-down':'heart'}"></i><span>${r.votes}</span></button>`:''}</div>`).join('')||'<p class="square-empty">本周还没有上榜菜品</p>';}
export async function renderSocial(root){
 const [rank,feed,posts,catalog]=await Promise.all([api('/social/rankings'),api('/social/feed'),api('/social/posts'),api('/workspace/catalog')]);
 if(location.hash!=='#social')return;
 const menuImages = new Map(catalog.data.dishes.map(d=>[d.id,d.image]));
 const entries=[...feed.data.map(r=>({...r,kind:'reviews'})),...posts.data.map(r=>({...r,kind:'posts'}))].sort((a,b)=>new Date(b.addtime)-new Date(a.addtime));
 root.innerHTML=`<header class="square-heading"><h1>食话广场</h1><p>你的饭搭子情报站 · 认真吃饭，快乐吐槽。</p><small>每周一更新 · 本期 ${esc(rank.data.week)} · 统计 ${esc(rank.data.period)}</small></header><section class="square-boards">${boards.map(([key,title,icon])=>`<button class="square-board ${key}" data-action="ranking" data-key="${key}"><h2><i class="fa-solid fa-${icon}" aria-hidden="true"></i> ${title}</h2>${rankRows(rank.data[key].slice(0,3),key)}<small class="square-more">查看本周榜单 →</small></button>`).join('')}</section><div class="square-feed-heading"><h2>最新动态</h2>${button('🍱 分享用餐日常','share',true)}${button('📝 发表菜品评价','publish')}</div><section class="square-feed">${entries.map(r=>`<article class="square-post"><header><span class="square-avatar">${esc(r.username.slice(0,1))}</span><div><b>${esc(r.username)}</b><small>${esc(dateTime(r.addtime))}</small></div>${stars(r.rating)}</header><p>${esc(r.content)}</p><small class="square-dish">${esc(r.dishName||'我的校园饭日记')}</small>${imageUrl(r.image || menuImages.get(r.dishId))?`<img src="${esc(imageUrl(r.image || menuImages.get(r.dishId)))}" alt="${esc(r.dishName||'用餐分享图片')}" loading="lazy">`:''}${r.reply?`<p class="square-reply">校方回复：${esc(r.reply)}</p>`:''}<footer><button data-action="comments" data-id="${r.id}" data-kind="${r.kind}"><i class="fa-regular fa-comment"></i> 评论${r.comments?' '+r.comments:''}</button><button data-action="like" data-id="${r.id}" data-kind="${r.kind}" aria-pressed="${Boolean(r.liked)}" class="${r.liked?'liked':''}"><i class="fa-${r.liked?'solid':'regular'} fa-heart"></i> ${r.likes}</button></footer></article>`).join('')||'<p class="square-empty">还没有分享，快来承包第一条动态吧。</p>'}</section><div data-status></div>`;
 const find=b=>entries.find(x=>String(x.id)===b.dataset.id&&x.kind===b.dataset.kind);
 bind(root,{
 ranking:b=>{const key=b.dataset.key,rows=rank.data[key];const d=dialog(boards.find(x=>x[0]===key)[1],`<p class="square-week-note">每周一更新榜单；收藏与点踩独立记录。箭头表示相较上期排名的变化。</p><section class="square-ranking-detail ${key}">${rankRows(rows,key,true)}</section><div data-status></div>`);bind(d,{vote:async btn=>{const r=rows.find(x=>String(x.id)===btn.dataset.id);const response=await api(`/social/dishes/${r.id}/vote`,{method:'POST',body:{kind:key==='pitfall'?'down':'favorite',active:!r.voted}});r.voted=response.data.active;r.votes=response.data.count;btn.setAttribute('aria-pressed',String(r.voted));btn.classList.toggle('liked',r.voted);btn.classList.remove('heart-pop');void btn.offsetWidth;btn.classList.add('heart-pop');btn.innerHTML=`<i class="fa-${r.voted?'solid':'regular'} fa-${key==='pitfall'?'thumbs-down':'heart'}"></i><span>${r.votes}</span>`;}});},
 like:async b=>{const r=find(b);await api(`/social/${r.kind}/${r.id}/like`,{method:'POST',body:{liked:!r.liked}});r.liked=!r.liked;r.likes+=r.liked?1:-1;b.setAttribute('aria-pressed',String(Boolean(r.liked)));b.classList.toggle('liked',Boolean(r.liked));b.classList.add('heart-pop');b.innerHTML=`<i class="fa-${r.liked?'solid':'regular'} fa-heart"></i> ${r.likes}`;},
 share:()=>{const d=dialog('晒晒今天的饭 🍱',`<form>${field('dishId','关联菜品（可选）',`<select>${options([['','不关联菜品'],...catalog.data.dishes.map(x=>[x.id,x.name+' · '+x.restaurant])])}</select>`)}${field('content','分享你的用餐日常','<textarea required maxlength="2000" placeholder="食堂奇遇、饭搭子故事，今天有什么值得分享？"></textarea>')}<label class="zx-field">配张图更有味道<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></label><img data-preview hidden style="max-height:220px;border-radius:16px"><button class="zx-button zx-primary">发布分享</button><div data-status></div></form>`);let image='';d.querySelector('[name="photo"]').onchange=async e=>{image='';const file=e.target.files[0],preview=d.querySelector('[data-preview]');preview.hidden=true;if(!file)return;if(file.size>1500000||!['image/png','image/jpeg','image/webp'].includes(file.type)){e.target.value='';d.querySelector('[data-status]').innerHTML=notice('请选择不超过1.5MB的PNG、JPEG或WebP图片','error');return;}image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});preview.src=image;preview.hidden=false;};submit(d,async body=>{await api('/social/posts',{method:'POST',body:{content:body.content,dishId:body.dishId,image}});d.close();await renderSocial(root);});},
 publish:()=>{const d=dialog('发表菜品评价',`<form>${field('dishId','菜品',`<select required>${options(catalog.data.dishes.map(x=>[x.id,x.name+' · '+x.restaurant+' '+(x.floor||'')]))}</select>`)}${field('rating','评分',`<select>${options([[5,'★★★★★ 很满意'],[4,'★★★★☆ 满意'],[3,'★★★☆☆ 一般'],[2,'★★☆☆☆ 不满意'],[1,'★☆☆☆☆ 不推荐']])}</select>`)}${field('content','就餐体验','<textarea required maxlength="2000" placeholder="分享菜品口味、份量或服务体验"></textarea>')}<button class="zx-button zx-primary">发布评价</button><div data-status></div></form>`);submit(d,async body=>{await api('/social/reviews',{method:'POST',body});d.close();await renderSocial(root);});},
 comments:async b=>{const r=find(b),data=(await api(`/social/${r.kind}/${r.id}/comments`)).data;const d=dialog('饭搭子留言 · '+(r.dishName||'用餐日常'),`<p>${esc(r.content)}</p><div class="square-comments">${data.map(c=>`<p><b>${esc(c.username.replace(/（模拟）$/, ''))}</b><br>${esc(c.content)}</p>`).join('')||'<p>还没人接话，来当第一个饭搭子。</p>'}</div><form>${field('content','发表评论','<textarea required maxlength="2000"></textarea>')}<button class="zx-button zx-primary">发表</button><div data-status></div></form>`);submit(d,async body=>{await api(`/social/${r.kind}/${r.id}/comments`,{method:'POST',body});d.close();await renderSocial(root);});}
 });
}
function submit(d,action){d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await action(formData(e.target));}catch(err){d.querySelector('[data-status]').innerHTML=notice(err.message,'error');}finally{b.disabled=false;}};}
