import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import request from 'supertest';
import { targetFor } from './support/target.js';
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'zhixiang-demo-'));
for(const name of fs.readdirSync(new URL('../../userdata/',import.meta.url)))if(/\.(json|csv)$/.test(name))fs.copyFileSync(new URL('../../userdata/'+name,import.meta.url),path.join(temporary,name));
process.env.DB_PATH=':memory:';process.env.USERDATA_DIR=temporary;process.env.SEED_REFERENCE_DATA='false';process.env.DEEPSEEK_API_KEY='';
const {default:app}=await import('../app.js');
const {mainDb}=await import('../database.js');
const {closeDemoConnections}=await import('../services/demoEnvironment.js');
const target=await targetFor(app);
const get=(url,token)=>request(target).get(url).set('Authorization','Bearer '+token);
const post=(url,token,body)=>request(target).post(url).set('Authorization','Bearer '+token).send(body);
let first,second;
after(()=>{closeDemoConnections();mainDb.close();fs.rmSync(temporary,{recursive:true,force:true});});
test('学校列表保持三校，正式校方不可免认证注册，演示无需个人信息',async()=>{
  const schools=await request(target).get('/api/users/schools');assert.equal(schools.body.data.length,3);assert.ok(!schools.body.data.some(s=>s.id==='demo'));
  const rejected=await request(target).post('/api/users/register').send({schoolId:'cufe',identity:'admin',trial:true,zhanghao:'badtrial',mima:'password-123',xingming:'测试'});assert.equal(rejected.status,403);
  const response=await request(target).post('/api/demo/session').send({});assert.equal(response.status,200,JSON.stringify(response.body));first=response.body.data;
  assert.equal(first.user.school_id,'demo');assert.equal(first.school.name,'演示数据');assert.equal(first.user.role,'admin');assert.equal(mainDb.prepare("SELECT COUNT(*) n FROM yonghu WHERE school_id='demo'").get().n,0);
});
test('演示数据180天关联，图表、台账与小智读取同一会话',async()=>{
  const catalog=await get('/api/workspace/catalog',first.token);assert.equal(catalog.status,200);assert.equal(catalog.body.data.restaurants.length,4);assert.equal(catalog.body.data.dishes.length,48);assert.ok(catalog.body.data.dishes.every(d=>d.schoolId==='demo'&&d.restaurantId));
  const response=await get('/api/demo/insights',first.token);assert.equal(response.status,200,JSON.stringify(response.body));const data=response.body.data;
  assert.ok(data.summary.orders>0);assert.ok(data.safety.checks>0);assert.equal(data.matrix.length,12);assert.equal(data.suppliers.length,4);
  await post('/api/demo/clock',first.token,{scene:'lunch',playing:false});
  const paused=(await get('/api/demo/insights',first.token)).body.data;assert.equal(paused.clock.minute,705);
  const chat=await post('/api/ai/chat',first.token,{message:'查看供需矩阵和人流热点',surface:'management'});assert.equal(chat.status,200);assert.ok(chat.body.reply.includes('演示数据'));assert.ok(chat.body.reply.includes('11:45'));assert.ok(!chat.body.reply.includes('中央财经大学'));
  assert.equal((await post('/api/ai/chat',first.token,{message:'点餐',surface:'student'})).status,403);
  assert.equal((await post('/api/tasks/conversation',first.token,{message:'点餐'})).status,403);
  const filtered=(await get('/api/demo/insights?campus='+encodeURIComponent('东校区'),first.token)).body.data;assert.equal(filtered.traffic.length,2);assert.equal(filtered.matrix.length,6);
  assert.equal((await get('/api/demo/insights?from=bad',first.token)).status,400);
});
test('访客写入及场景互相隔离，不能读取正式数据或使用开发入口',async()=>{
  second=(await request(target).post('/api/demo/session').send({})).body.data;
  assert.notEqual(first.user.demoSession,second.user.demoSession);
  const dishes=(await get('/api/workspace/catalog',first.token)).body.data.dishes;const dish=dishes[0];
  const update=await request(target).put('/api/dishes/'+dish.id).set('Authorization','Bearer '+first.token).send({stock:7});assert.equal(update.status,200);
  assert.equal((await get('/api/workspace/catalog',first.token)).body.data.dishes[0].stock,7);
  assert.notEqual((await get('/api/workspace/catalog',second.token)).body.data.dishes[0].stock,7);
  assert.equal(mainDb.prepare('SELECT 1 FROM caipinxinxi WHERE id=?').get(dish.id),undefined);
  for(const route of ['development-account','development-session'])assert.equal((await post('/api/users/'+route,first.token,{schoolId:'cufe'})).status,403);
  const blocked=await post('/api/users/login',first.token,{zhanghao:'demo_guest',mima:'!禁止密码登录',schoolId:'demo',identity:'admin'});assert.equal(blocked.status,401);
  const otherClock=(await get('/api/demo/insights',second.token)).body.data.clock;assert.equal(otherClock.playing,true);
  closeDemoConnections();assert.equal((await get('/api/workspace/catalog',first.token)).body.data.dishes[0].stock,7);
});
